---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: knativequarkusvoter-processor
    app.kubernetes.io/version: 1.0.1-SNAPSHOT
  name: knativequarkusvoter-processor
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: knativequarkusvoter-processor
    app.kubernetes.io/version: 1.0.1-SNAPSHOT
    app.kubernetes.io/part-of: knativequarkusvoter
  name: knativequarkusvoter-processor
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: knativequarkusvoter-processor
        app.kubernetes.io/version: 1.0.1-SNAPSHOT
      annotations:
        autoscaling.knative.dev/minScale: '1'
        autoscaling.knative.dev/maxScale: '1'
    spec:
      containerConcurrency: 0
      containers:
        - image: quay.io/kevindubois/knativequarkusvoter-processor
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 0
              scheme: HTTP
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          imagePullPolicy: IfNotPresent
          name: knativequarkusvoter-processor
          ports:
            - containerPort: 8080
              name: http1
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 0
              scheme: HTTP
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
      serviceAccountName: knativequarkusvoter-processor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: view-secrets
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: knativequarkusvoter-processor-view
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
  - kind: ServiceAccount
    name: knativequarkusvoter-processor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: knativequarkusvoter-processor-view-secrets
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: view-secrets
subjects:
  - kind: ServiceAccount
    name: knativequarkusvoter-processor
